import Head from 'next/head'
import {  LogButton, LogInputSearch } from '../components/webcomponents'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Logistic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/logo.png" />
      </Head>

      <main>
        <LogInputSearch  />
      </main>

    </div>
  )
}
