import Head from 'next/head'
import {  LogInput, LogInputSearch } from '../components/stencil-generated'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Logistic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LogInputSearch>
          <span>Pesquisar</span>
        </LogInputSearch>
      </main>

    </div>
  )
}
